Repository DependencyTrack/hyades, pull requests merged in 2023-10, with the labels that each got.

#839 bump kafka lib version
  commons-kstreams/src/test/java/org/hyades/kstreams/statestore/StateStoreUtilTest.java
  pom.xml
Labels: dependencies, java

#852 Fix failing `setup-graalvm` action
  .github/workflows/ci.yml
Labels: bug 🐛, ci 🛠️

#855 Remove dependency on `cyclonedx-core-java`
  pom.xml
Labels: dependencies, java

#829 Add documentation for CEL policies
  CONFIGURATION.md
  docker-compose.yml
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  docs/TOPICS.md
  docs/about.md
  docs/architecture/design/workflow-state-tracking.md
  docs/architecture/overview.md
  docs/images/usage/policy-compliance/expression-condition.png
  docs/reference/configuration.md
  docs/reference/topics.md
  docs/repository-meta-analyzer/README.md
  docs/usage/policy-compliance/expressions.md
  docs/usage/policy-compliance/overview.md
  docs/vulnerability-analyzer/README.md
  mkdocs.yml
  scripts/docs-dev.sh
Labels: documentation 📃

#859 Bump CWE dictionary to v4.12
  commons/src/main/java/org/hyades/common/cwe/CweDefinitions.java
  scripts/generate-cwe-definitions.py
Labels: enhancement 🚀

#861 Fix false negatives in NVD CPE matching
  commons-persistence/pom.xml
  commons-persistence/src/main/java/org/hyades/persistence/repository/VulnerableSoftwareRepository.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/internal/InternalScannerProcessorTest.java
Labels: bug 🐛, domain/vuln-analysis 🕵

#868 Build and publish docs upon release
  .github/workflows/deploy-docs.yml
Labels: documentation 📃, ci 🛠️

#867 Build and publish native images on release
  .github/workflows/_build-native-meta.yml
  .github/workflows/build-native-mirror-service.yml
  .github/workflows/build-native-notification-publisher.yml
  .github/workflows/build-native-repository-meta-analyzer.yml
  .github/workflows/build-native-vulnerability-analyzer.yml
Labels: enhancement 🚀, ci 🛠️

#870 Include Cloud SQL database connector for PostgreSQL
  commons-persistence/pom.xml
  pom.xml
Labels: enhancement 🚀

#877 Increase timeout of test workflows
  .github/workflows/ci.yml
Labels: ci 🛠️

#878 Fix `repartition.purge.interval.ms` not being configurable via environment variables
  mirror-service/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: bug 🐛, domain/repo-meta-analysis 🔄, domain/vuln-analysis 🕵, domain/vuln-mirroring 🪞

#882 Bump frontend to `4.9.0`
  docker-compose.yml
  helm-charts/hyades/values.yaml
Labels: dependencies, docker
