Repository DependencyTrack/hyades, pull requests merged in 2023-04, with the labels that each got.

#463 Enable Snappy compression for notification-publisher and repository-meta-analyzer
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
Labels: enhancement 🚀, domain/notifications 📢, domain/repo-meta-analysis 🔄

#458 Provide OSS Index credentials to E2E tests; Increase timeout
  .github/workflows/publishJar.yml
  e2e/src/test/java/org/hyades/e2e/BomUploadOssIndexAnalysisE2ET.java
  e2e/src/test/java/org/hyades/e2e/BomUploadSnykAnalysisE2ET.java
Labels: qa ⚖, ci 🛠️

#471 Add `TOPICS.md`
  TOPICS.md
Labels: documentation 📃

#479 Cleanup
  .kodiak.toml
  commons/src/main/java/org/hyades/common/KafkaTopic.java
  commons/src/main/java/org/hyades/model/Analysis.java
  commons/src/main/java/org/hyades/model/AnalysisComment.java
  commons/src/main/java/org/hyades/model/AnalysisJustification.java
  commons/src/main/java/org/hyades/model/AnalysisResponse.java
  commons/src/main/java/org/hyades/model/AnalysisState.java
  commons/src/main/java/org/hyades/model/AnalyzerIdentity.java
  commons/src/main/java/org/hyades/model/Bom.java
  commons/src/main/java/org/hyades/model/ComponentAnalysisCache.java
  commons/src/main/java/org/hyades/model/FindingAttribution.java
  commons/src/main/java/org/hyades/model/Policy.java
  commons/src/main/java/org/hyades/model/PolicyCondition.java
  commons/src/main/java/org/hyades/model/PolicyViolation.java
  commons/src/main/java/org/hyades/model/Project.java
  commons/src/main/java/org/hyades/model/Vex.java
  commons/src/main/java/org/hyades/model/ViolationAnalysis.java
  commons/src/main/java/org/hyades/model/ViolationAnalysisComment.java
  commons/src/main/java/org/hyades/model/ViolationAnalysisState.java
  commons/src/main/java/org/hyades/model/Vulnerability.java
  commons/src/main/java/org/hyades/model/VulnerabilityAnalysisLevel.java
  commons/src/main/java/org/hyades/model/VulnerabilityScanKey.java
  commons/src/main/java/org/hyades/model/VulnerabilityScanResult.java
  commons/src/main/java/org/hyades/model/VulnerabilityScanStatus.java
  commons/src/main/java/org/hyades/persistence/CacheTypeConverter.java
  commons/src/main/java/org/hyades/persistence/ConfigPropertyRepository.java
  commons/src/main/java/org/hyades/persistence/TeamRepository.java
  commons/src/main/java/org/hyades/resource/CweResource.java
  commons/src/test/java/org/hyades/common/KafkaTopicTest.java
  commons/src/test/java/org/hyades/model/AnalysisCommentTest.java
  commons/src/test/java/org/hyades/model/AnalysisStateTest.java
  commons/src/test/java/org/hyades/model/AnalysisTest.java
  commons/src/test/java/org/hyades/model/BomTest.java
  commons/src/test/java/org/hyades/model/PolicyConditionTest.java
  commons/src/test/java/org/hyades/model/PolicyTest.java
  commons/src/test/java/org/hyades/persistence/CacheTypeConverterTest.java
  load-tests/.gitignore
  load-tests/Makefile
  load-tests/README.md
  load-tests/package-lock.json
  load-tests/package.json
  load-tests/repo-meta-analyzer.js
  load-tests/tsconfig.json
  load-tests/vuln-analyzer.js
  load-tests/xk6-kafka.d.ts
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/osv/OsvMirror.java
  mirror-service/src/test/java/org/hyades/vulnmirror/state/VulnerabilityDigestStoreTest.java
  notification-publisher/src/main/java/org/hyades/notification/NotificationRouter.java
  notification-publisher/src/main/java/org/hyades/notification/persistence/NotificationRuleRepository.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/Publisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/PublisherException.java
  repository-meta-analyzer/src/main/java/org/hyades/persistence/RepoEntityRepository.java
  vulnerability-analyzer/src/main/java/org/hyades/persistence/VulnerableSoftwareRepository.java
Labels: enhancement 🚀, technical debt 💸

#484 Port `BOM_PROCESSING_FAILED` notification from upstream
  notification-publisher/src/main/java/org/hyades/notification/NotificationRouter.java
  notification-publisher/src/main/java/org/hyades/notification/model/NotificationGroup.java
  notification-publisher/src/main/java/org/hyades/util/ModelConverter.java
  notification-publisher/src/test/java/org/hyades/notification/NotificationRouterTest.java
  proto/src/main/proto/org/hyades/notification/v1/notification.proto
Labels: enhancement 🚀, domain/notifications 📢

#464 Emit a single result event for vulnerability scans
  TOPICS.md
  docker-compose.yml
  docs/vuln-analyzer_scan-results.png
  docs/vuln-analyzer_topology.png
  proto/src/main/proto/org/hyades/vulnanalysis/internal/v1beta1/vuln_analysis_internal.proto
  proto/src/main/proto/org/hyades/vulnanalysis/v1/vuln_analysis.proto
  scripts/create-topics.sh
  vulnerability-analyzer/README.md
  vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/ScanProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/internal/InternalScannerProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/ossindex/OssIndexProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/snyk/SnykProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/scanner/snyk/SnykProcessorSupplier.java
  vulnerability-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerIT.java
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerTopologyTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/internal/InternalScannerProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/ossindex/OssIndexProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/snyk/SnykProcessorTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#497 Bump Redpanda
  docker-compose.yml
Labels: documentation 📃

#496 Bump frontend for demo setup to 4.8.0
  docker-compose.yml
Labels: documentation 📃

#514 backported enhancement from 2396
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/AuthorizationClientHeaderFactory.java
  vulnerability-analyzer/src/test/java/org/hyades/client/snyk/AuthorizationClientHeaderFactoryTest.java
  vulnerability-analyzer/src/test/java/org/hyades/client/snyk/ModelConverterTest.java
  vulnerability-analyzer/src/test/java/org/hyades/client/snyk/SnykClientTest.java
Labels: enhancement 🚀

#520 Increase timeout of `test` job to 25 minutes
  .github/workflows/ci.yml
Labels: ci 🛠️

#521 Ensure timestamps for Go modules are parsed as UTC
  repository-meta-analyzer/src/main/java/org/hyades/repositories/GoModulesMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerIT.java
Labels: bug 🐛, domain/repo-meta-analysis 🔄

#511 build(deps): bump open-vulnerability-clients from 3.0.0 to 4.0.1
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  pom.xml
Labels: enhancement 🚀, domain/vuln-mirroring 🪞

#523 Remove CodeQL workflow
  .github/workflows/codeql.yml
Labels: ci 🛠️

#524 Fix incorrect `contains` check in `ModelConverter#compareSeverities`
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ModelConverter.java
Labels: bug 🐛, domain/vuln-analysis 🕵

#528 Add `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md`, and `SECURITY.md`
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation 📃
