Repository DependencyTrack/hyades, pull requests merged in 2023-02, with the labels that each got.

#292 Fix `NugetMetaAnalyzer` reporting `MetaModel.component` as `null`
  repository-meta-analyzer/src/main/java/org/hyades/repositories/NugetMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/NugetMetaAnalyzerTest.java
Labels: bug 🐛, domain/repo-meta-analysis 🔄

#298 Disable database features for mirror service
  mirror-service/pom.xml
  mirror-service/src/main/resources/application.properties
Labels: enhancement 🚀, domain/vuln-mirroring

#313 Add `LICENSE`
  LICENSE
Labels: meta 👽

#314 Add basic checkstyle config
  .checkstyle.xml
  commons/pom.xml
  commons/src/main/java/org/hyades/common/HttpClientConfiguration.java
  commons/src/main/java/org/hyades/model/ConfigProperty.java
  mirror-service/pom.xml
  mirror-service/src/main/java/org/hyades/MirrorServiceTopology.java
  notification-publisher/pom.xml
  notification-publisher/src/main/java/org/hyades/notification/NotificationRouter.java
  notification-publisher/src/main/java/org/hyades/util/NotificationUtil.java
  pom.xml
  repository-meta-analyzer/pom.xml
  repository-meta-analyzer/src/main/java/org/hyades/model/Repository.java
  vulnerability-analyzer/pom.xml
  vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessorSupplier.java
Labels: enhancement 🚀, ci 🛠️

#312 Avoid repartition caused by tombstone emitters
  vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/misc/TombstoneEmittingProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/misc/TombstoneEmittingProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/util/FixedKeyRecordFactory.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/misc/TombstoneEmittingProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/util/FixedKeyRecordFactoryTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#324 Re-enable SonarCloud
  .github/workflows/ci.yml
  pom.xml
Labels: enhancement 🚀, ci 🛠️

#332 Removed snykHttpClient bean
  monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykClientConfiguration.java
Labels: domain/vuln-analysis 🕵

#336 Update SonarCloud organization and project key
  pom.xml
Labels: ci 🛠️

#337 Add protobuf serializers and schemas for vulnerability analysis domain
  .github/workflows/_build-native-meta.yml
  .github/workflows/ci.yml
  pom.xml
  proto/pom.xml
  proto/src/main/java/org/hyades/proto/JacksonProtobufDeserializer.java
  proto/src/main/java/org/hyades/proto/JacksonProtobufSerializer.java
  proto/src/main/java/org/hyades/proto/KafkaProtobufDeserializer.java
  proto/src/main/java/org/hyades/proto/KafkaProtobufSerde.java
  proto/src/main/java/org/hyades/proto/KafkaProtobufSerializer.java
  proto/src/main/proto/vuln-analysis-internal_v1.proto
  proto/src/main/proto/vuln-analysis_v1.proto
  proto/src/main/proto/vuln_v1.proto
  proto/src/test/java/org/hyades/proto/JacksonProtobufDeserializerTest.java
  proto/src/test/java/org/hyades/proto/JacksonProtobufSerializerTest.java
  proto/src/test/java/org/hyades/proto/KafkaProtobufSerdeTest.java
  vulnerability-analyzer/pom.xml
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/SnykClientConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/serde/ObjectMapperCustomizer.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/snyk/SnykProcessorTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#342 Re-enable SonarCloud badges in `README.md`
  README.md
Labels: documentation 📃
