Repository DependencyTrack/hyades, pull requests merged in 2023-01, with the labels that each got.

#188 Simplify handling of secret key
  .gitignore
  DEMO.md
  README.md
  commons/src/main/java/org/acme/common/SecretDecryptor.java
  commons/src/main/java/org/acme/common/SecretDecryptorConfiguration.java
  commons/src/main/java/org/acme/commonutil/SecretsUtil.java
  commons/src/test/java/org/acme/common/SecretDecryptorTest.java
  commons/src/test/resources/application.properties
  commons/src/test/resources/secret.key
  docker-compose.yml
  repository-meta-analyzer/src/main/java/org/acme/RepositoryMetaAnalyzerTopology.java
  repository-meta-analyzer/src/main/resources/application.properties
  repository-meta-analyzer/src/test/resources/secret.key
  scripts/gen-secret-key.jsh
Labels: documentation 📃, enhancement 🚀, domain/repo-meta-analysis 🔄

#189 Add script to generate test fixture BOMs for load testing
  .gitignore
  load-tests/Makefile
  load-tests/fixtures/generate.sh
  load-tests/fixtures/images.txt
Labels: qa ⚖

#195 Fix build of container image for native executable
  .github/workflows/publishNativeBinary.yml
Labels: bug 🐛, domain/vuln-analysis 🕵

#196 Use GH Action to build and push container image in one step
  .github/workflows/publishNativeBinary.yml
Labels: bug 🐛, domain/vuln-analysis 🕵

#201 Register RetryableRecord.JsonRecordHeader for reflection
  vulnerability-analyzer/src/main/java/org/acme/processor/retry/RetryableRecord.java
Labels: bug 🐛, domain/vuln-analysis 🕵

#200 Snyk: skip unsupported PURL types
  vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessor.java
  vulnerability-analyzer/src/test/java/org/acme/processor/snyk/SnykProcessorTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#202 Add health-, ready-, and liveness checks for vuln analyzer
  vulnerability-analyzer/pom.xml
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#205 Export request duration metrics for Snyk HTTP client
  vulnerability-analyzer/src/main/java/org/acme/client/snyk/SnykClientConfiguration.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#207 Unify metric and tag names
  vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/acme/processor/retry/RetryingProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessorConfiguration.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#211 Add Grafana dashboard for vulnerability analyzer
  docker-compose.yml
  load-tests/README.md
  monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
  monitoring/prometheus.yml
  scripts/profile-loadtest.sh
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#216 Fix load test fixture generation
  load-tests/fixtures/generate.sh
  load-tests/fixtures/images.txt
  load-tests/vuln-analyzer.js
Labels: bug 🐛, qa ⚖

#214 Support multiple instances in vuln analyzer Grafana dashboard
  monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
  vulnerability-analyzer/src/main/java/org/acme/processor/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/internal/InternalScannerProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessor.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#236 Workaround for buildx build failures
  .github/workflows/publishJar.yml
  mirror-service/pom.xml
Labels: ci 🛠️

#238 Add missing Dockerfiles for mirror-service
  mirror-service/src/main/docker/Dockerfile.jvm
  mirror-service/src/main/docker/Dockerfile.legacy-jar
  mirror-service/src/main/docker/Dockerfile.native
  mirror-service/src/main/docker/Dockerfile.native-micro
Labels: ci 🛠️

#237 Remove last traces of Alpine
  commons/pom.xml
  commons/src/main/java/org/acme/model/Cwe.java
  commons/src/main/java/org/acme/model/NotificationRule.java
  commons/src/main/java/org/acme/model/Project.java
  commons/src/main/java/org/acme/model/Tag.java
  commons/src/main/java/org/acme/model/VulnerabilityAlias.java
  commons/src/main/java/org/acme/persistence/CollectionIntegerConverter.java
  commons/src/main/java/org/acme/persistence/CweImporter.java
  notification-publisher/src/main/java/org/acme/notification/publisher/AbstractWebhookPublisher.java
  notification-publisher/src/main/java/org/acme/notification/publisher/ConsolePublisher.java
  notification-publisher/src/main/java/org/acme/notification/publisher/Publisher.java
  notification-publisher/src/main/java/org/acme/notification/publisher/SendMailPublisher.java
  pom.xml
  repository-meta-analyzer/src/main/java/org/acme/repositories/AbstractMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/ComposerMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/GemMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/GoModulesMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/HexMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/MavenMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/NpmMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/NugetMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/acme/repositories/PypiMetaAnalyzer.java
Labels: enhancement 🚀, technical debt 💸

#235 Update `CONFIGURATION.md`
  CONFIGURATION.md
Labels: documentation 📃

#241 Fix Maven repo meta analysis failing with native image
  repository-meta-analyzer/pom.xml
Labels: bug 🐛, domain/repo-meta-analysis 🔄

#242 Cleanup dependency management
  commons/pom.xml
  mirror-service/pom.xml
  notification-publisher/pom.xml
  pom.xml
  repository-meta-analyzer/pom.xml
  vulnerability-analyzer/pom.xml
Labels: enhancement 🚀

#243 Use native images for demo Compose setup
  docker-compose.yml
Labels: enhancement 🚀

#246 Use pre-built API server container image for demo
  DEMO.md
  docker-compose.yml
Labels: documentation 📃, enhancement 🚀

#251 bugfix/fix-documentation
  DEMO.md
Labels: documentation 📃

#219 Tracking of scanner completion with Kafka Streams
  commons/src/main/java/org/acme/common/KafkaTopic.java
  commons/src/main/java/org/acme/model/AnalyzersConfig.java
  commons/src/main/java/org/acme/model/VulnerabilityResult.java
  commons/src/main/resources/migrations/postgres/V0.0.1__API-Server-4.7.0-SNAPSHOT.sql
  commons/src/test/java/org/acme/model/VulnerabilityResultTest.java
  docker-compose.yml
  load-tests/repo-meta-analyzer.js
  load-tests/vuln-analyzer.js
  monitoring/grafana/dashboards/apiserver_dashboard.json
  renovate.json
  scripts/create-topics.sh
  vulnerability-analyzer/pom.xml
  vulnerability-analyzer/src/main/java/org/acme/VulnerabilityAnalyzerTopology.java
  vulnerability-analyzer/src/main/java/org/acme/config/InternalScannerConfig.java
  vulnerability-analyzer/src/main/java/org/acme/config/OssIndexConfig.java
  vulnerability-analyzer/src/main/java/org/acme/config/SnykConfig.java
  vulnerability-analyzer/src/main/java/org/acme/model/CompletedScans.java
  vulnerability-analyzer/src/main/java/org/acme/model/ExpectedScanResults.java
  vulnerability-analyzer/src/main/java/org/acme/model/ScanKey.java
  vulnerability-analyzer/src/main/java/org/acme/model/ScanResult.java
  vulnerability-analyzer/src/main/java/org/acme/model/ScanStatus.java
  vulnerability-analyzer/src/main/java/org/acme/model/ScanTask.java
  vulnerability-analyzer/src/main/java/org/acme/processor/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/internal/InternalScannerProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/acme/processor/misc/TombstoneEmittingProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/misc/TombstoneEmittingProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/acme/processor/ossindex/OssIndexProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessor.java
  vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/acme/processor/snyk/SnykProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/acme/serializers/ScanKeyDeserializer.java
  vulnerability-analyzer/src/main/java/org/acme/serializers/ScanKeySerde.java
  vulnerability-analyzer/src/main/java/org/acme/serializers/ScanKeySerializer.java
  vulnerability-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/test/java/org/acme/VulnerabilityAnalyzerTopologyTest.java
  vulnerability-analyzer/src/test/java/org/acme/client/ossindex/AuthorizationClientHeaderFactoryTest.java
  vulnerability-analyzer/src/test/java/org/acme/processor/internal/InternalScannerProcessorTest.java
  vulnerability-analyzer/src/test/java/org/acme/processor/misc/TombstoneEmittingProcessorTest.java
  vulnerability-analyzer/src/test/java/org/acme/processor/ossindex/OssIndexProcessorTest.java
  vulnerability-analyzer/src/test/java/org/acme/processor/snyk/SnykProcessorTest.java
Labels: domain/vuln-analysis 🕵

#255 Build and publish native executables for amd64 and arm64
  .github/workflows/_build-native-meta.yml
  .github/workflows/build-native-notification-publisher.yml
  .github/workflows/build-native-repository-meta-analyzer.yml
  .github/workflows/build-native-vulnerability-analyzer.yml
  .github/workflows/publishNativeBinaryNotification.yml
  .github/workflows/publishNativeBinaryRepoMetaAnalyzer.yml
  .github/workflows/publishNativeBinaryVulnAnalyzer.yml
  notification-publisher/.dockerignore
  notification-publisher/src/main/docker/Dockerfile.native-multiarch
  repository-meta-analyzer/.dockerignore
  repository-meta-analyzer/src/main/docker/Dockerfile.native-multiarch
  vulnerability-analyzer/.dockerignore
  vulnerability-analyzer/src/main/docker/Dockerfile.native-multiarch
Labels: enhancement 🚀, ci 🛠️

#257 Add justifications for various architectural decisions
  README.md
  WTF.md
  docs/dependencytrack-executorservice.png
Labels: documentation 📃

#260 Fix sonar project key
  README.md
  pom.xml
Labels: bug 🐛, ci 🛠️

#263 Fix ClassNotFoundException in Caffeine for native image
  commons/src/main/java/org/hyades/common/CaffeineReflectionConfiguration.java
Labels: bug 🐛

#264 Build multi-platform images for jar-based distribution
  .github/workflows/publishJar.yml
Labels: bug 🐛, ci 🛠️

#265 Fix various links; Adjust various names
  .github/dependabot.yml
  CONFIGURATION.md
  DEMO.md
  MINIKUBE.md
  README.md
  WTF.md
  commons/pom.xml
  docker-compose.yml
  load-tests/fixtures/images.txt
  mirror-service/src/main/resources/application.properties
  notification-publisher/pom.xml
  notification-publisher/src/main/resources/application.properties
  renovate.json
  repository-meta-analyzer/pom.xml
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/pom.xml
  vulnerability-analyzer/src/main/resources/application.properties
Labels: documentation 📃

#266 Fix container image repo name; Do not push on forks
  .github/workflows/_build-native-meta.yml
  .github/workflows/publishJar.yml
Labels: bug 🐛, ci 🛠️

#276 Limit dependabot Maven ecosystem to root directory
  .github/dependabot.yml
Labels: ci 🛠️

#275 Compose: Add frontend container; Increase default stream threads to 3
  DEMO.md
  docker-compose.yml
Labels: documentation 📃, enhancement 🚀
