Repository DependencyTrack/hyades, pull requests merged in 2023-11, with the labels that each got.

#892 Compose: Use `latest` for Hyades images; Bump frontend to `4.9.1`
  docker-compose.yml
Labels: dependencies, docker, deployment 🏗

#893 Bump frontend in Helm chart to `4.9.1`
  helm-charts/hyades/README.md
  helm-charts/hyades/values.yaml
Labels: deployment 🏗

#894 Update README.md
  README.md
Labels: documentation 📃

#897 Align Protobuf version with API server
  pom.xml
Labels: dependencies, java

#902 Reduce default HTTP client timeouts
  commons/src/main/java/org/hyades/config/HttpClientConfig.java
Labels: enhancement 🚀

#910 Update documentation
  DEMO.md
  README.md
  WTF.md
  vulnerability-analyzer/README.md
Labels: documentation 📃

#913 Fix line break issues when cloning repository on Windows
  .gitattributes
Labels: bug 🐛

#915 Mention native image variants in demo Compose setup
  docker-compose.yml
Labels: documentation 📃

#914 Enable CEL policy engine and integrity analysis per default in demo setup
  docker-compose.yml
Labels: documentation 📃

#916 Use custom frontend with CEL and integrity analysis support
  docker-compose.yml
  helm-charts/hyades/README.md
  helm-charts/hyades/templates/_helpers.tpl
  helm-charts/hyades/values.yaml
Labels: frontend

#921 Update docs policy expressions
  docs/usage/policy-compliance/expressions.md
Labels: documentation 📃
