Repository DependencyTrack/hyades, pull requests merged in 2023-03, with the labels that each got.

#355 Provide empty fallback value for `API_TOPIC_PREFIX` in `create-topics.sh`
  commons/src/main/java/org/hyades/common/KafkaTopic.java
  commons/src/main/java/org/hyades/config/KafkaTopicConfig.java
  commons/src/test/java/org/hyades/common/KafkaTopicMockProducer.java
  commons/src/test/java/org/hyades/common/KafkaTopicTest.java
  mirror-service/src/test/java/org/hyades/MirrorServiceTopologyTest.java
  repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerTopologyTest.java
  scripts/create-topics.sh
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerTopologyTest.java
Labels: bug 🐛

#357 Remove mirroring of analyzer results
  mirror-service/src/main/java/org/hyades/MirrorServiceTopology.java
  mirror-service/src/main/java/org/hyades/analyzer/AnalyzerProcessor.java
  mirror-service/src/test/java/org/hyades/MirrorServiceTopologyTest.java
  mirror-service/src/test/java/org/hyades/analyzer/AnalyzerProcessorTest.java
Labels: enhancement 🚀, domain/vuln-mirroring

#351 Metrics trial
  commons/src/main/java/org/hyades/common/KafkaTopic.java
  metrics-service/pom.xml
  metrics-service/src/main/docker/Dockerfile.jvm
  metrics-service/src/main/docker/Dockerfile.native
  metrics-service/src/main/docker/Dockerfile.native-multiarch
  metrics-service/src/main/java/org/hyades/MetricsTopology.java
  metrics-service/src/main/java/org/hyades/metrics/model/ComponentMetrics.java
  metrics-service/src/main/java/org/hyades/metrics/model/Metrics.java
  metrics-service/src/main/java/org/hyades/metrics/model/PortfolioMetrics.java
  metrics-service/src/main/java/org/hyades/metrics/model/ProjectMetrics.java
  metrics-service/src/main/java/org/hyades/metrics/model/Status.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ComponentDeltaProcessor.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ComponentProcessorSupplier.java
  metrics-service/src/main/java/org/hyades/metrics/processor/DeltaProcessorConfiguration.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ProjectDeltaProcessor.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ProjectProcessorSupplier.java
  metrics-service/src/main/java/org/hyades/metrics/util/MetricsUtil.java
  metrics-service/src/main/resources/application.properties
  metrics-service/src/test/java/org/hyades/MetricsTopologyTest.java
  metrics-service/src/test/java/org/hyades/processor/ComponentDeltaProcessorTest.java
  metrics-service/src/test/java/org/hyades/processor/DeltaProcessorConfigurationInMemory.java
  metrics-service/src/test/java/org/hyades/processor/ProjectDeltaProcessorTest.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/AbstractWebhookPublisher.java
  pom.xml
  scripts/create-topics.sh
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerTopologyTest.java
Labels: enhancement 🚀

#338 Refactor `vulnerability-analyzer` to use Protobuf schemas
  docker-compose.yml
  proto/src/main/proto/vuln-analysis_v1.proto
  vulnerability-analyzer/README.md
  vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
  vulnerability-analyzer/src/main/java/org/hyades/client/ossindex/ModelConverter.java
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ModelConverter.java
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/Report.java
  vulnerability-analyzer/src/main/java/org/hyades/model/CompletedScans.java
  vulnerability-analyzer/src/main/java/org/hyades/model/ExpectedScanResults.java
  vulnerability-analyzer/src/main/java/org/hyades/model/ScanTask.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/internal/InternalScannerProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/misc/TombstoneEmittingProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/misc/TombstoneEmittingProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/serde/ProtoReflectionConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/serializers/CweSerializer.java
  vulnerability-analyzer/src/main/java/org/hyades/serializers/ScanKeyDeserializer.java
  vulnerability-analyzer/src/main/java/org/hyades/serializers/ScanKeySerde.java
  vulnerability-analyzer/src/main/java/org/hyades/serializers/ScanKeySerializer.java
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerIT.java
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerTopologyTest.java
  vulnerability-analyzer/src/test/java/org/hyades/client/ossindex/ModelConverterTest.java
  vulnerability-analyzer/src/test/java/org/hyades/client/snyk/ModelConverterTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/internal/InternalScannerProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/misc/TombstoneEmittingProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/ossindex/OssIndexProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/snyk/SnykProcessorTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#360 Add prefix
  metrics-service/src/main/resources/application.properties
Labels: enhancement 🚀, domain/metrics 📈

#361 Add native workflow for metrics service
  .github/dependabot.yml
  .github/workflows/build-native-metrics-service.yml
  .github/workflows/ci.yml
  docker-compose.yml
  metrics-service/src/main/resources/application.properties
Labels: domain/vuln-mirroring 🪞, ci 🛠️

#367 Increase timeout for arm64 native builds to 75 minutes
  .github/workflows/_build-native-meta.yml
Labels: bug 🐛, ci 🛠️

#371 Prevent Quarkus datasource dev services from starting for metrics service
  metrics-service/pom.xml
Labels: enhancement 🚀, domain/metrics 📈

#385 Reduce memory footprint of demo Compose setup
  docker-compose.yml
Labels: enhancement 🚀

#393 Fix JVM-based container images for arm64
  metrics-service/src/main/docker/Dockerfile.jvm
  mirror-service/src/main/docker/Dockerfile.jvm
  notification-publisher/src/main/docker/Dockerfile.jvm
  repository-meta-analyzer/src/main/docker/Dockerfile.jvm
  vulnerability-analyzer/src/main/docker/Dockerfile.jvm
Labels: bug 🐛, ci 🛠️

#395 Change protoc version
  pom.xml
  proto/pom.xml
Labels: enhancement 🚀, ci 🛠️

#409 Remove metrics service
  .github/dependabot.yml
  .github/workflows/build-native-metrics-service.yml
  .github/workflows/ci.yml
  docker-compose.yml
  metrics-service/pom.xml
  metrics-service/src/main/docker/Dockerfile.jvm
  metrics-service/src/main/docker/Dockerfile.native
  metrics-service/src/main/docker/Dockerfile.native-multiarch
  metrics-service/src/main/java/org/hyades/MetricsTopology.java
  metrics-service/src/main/java/org/hyades/metrics/model/VulnerabilityStatus.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ComponentDeltaProcessor.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ComponentProcessorSupplier.java
  metrics-service/src/main/java/org/hyades/metrics/processor/DeltaProcessorConfiguration.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ProjectDeltaProcessor.java
  metrics-service/src/main/java/org/hyades/metrics/processor/ProjectProcessorSupplier.java
  metrics-service/src/main/java/org/hyades/metrics/util/MetricsUtil.java
  metrics-service/src/main/resources/application.properties
  metrics-service/src/test/java/org/hyades/MetricsServiceIT.java
  metrics-service/src/test/java/org/hyades/MetricsTopologyTest.java
  metrics-service/src/test/java/org/hyades/metrics/processor/ComponentDeltaProcessorTest.java
  metrics-service/src/test/java/org/hyades/metrics/processor/DeltaProcessorConfigurationInMemory.java
  metrics-service/src/test/java/org/hyades/metrics/processor/ProjectDeltaProcessorTest.java
  metrics-service/src/test/java/org/hyades/metrics/util/MetricsUtilTest.java
  monitoring/grafana/dashboards/metrics-service_dashboard.json
  monitoring/prometheus.yml
  pom.xml
  proto/src/main/proto/metrics_v1.proto
  scripts/create-topics.sh
Labels: domain/metrics 📈

#408 Avoid erroneous WARN logs during Snyk analysis
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessor.java
Labels: bug 🐛, domain/vuln-analysis 🕵

#407 Map description of OSS Index vulnerabilities
  vulnerability-analyzer/src/main/java/org/hyades/client/ossindex/ModelConverter.java
  vulnerability-analyzer/src/test/java/org/hyades/client/ossindex/ModelConverterTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#411 Refactor repository meta analyzer to use Protobuf schemas
  README.md
  commons/src/main/java/org/hyades/common/KafkaTopic.java
  docker-compose.yml
  docs/repo-meta-analyzer_topology.png
  proto/src/main/proto/repo-meta-analysis_v1.proto
  repository-meta-analyzer/README.md
  repository-meta-analyzer/pom.xml
  repository-meta-analyzer/src/main/java/org/hyades/RepositoryMetaAnalyzerTopology.java
  repository-meta-analyzer/src/main/java/org/hyades/model/MetaAnalyzerCacheKey.java
  repository-meta-analyzer/src/main/java/org/hyades/model/MetaModel.java
  repository-meta-analyzer/src/main/java/org/hyades/model/Repository.java
  repository-meta-analyzer/src/main/java/org/hyades/persistence/RepoEntityRepository.java
  repository-meta-analyzer/src/main/java/org/hyades/processor/MetaAnalyzerProcessor.java
  repository-meta-analyzer/src/main/java/org/hyades/processor/MetaAnalyzerProcessorSupplier.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/AbstractMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/ComposerMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/GemMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/GoModulesMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/HexMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/IMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/MavenMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/NpmMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/NugetMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/PypiMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/hyades/repositories/RepositoryAnalyzerFactory.java
  repository-meta-analyzer/src/main/java/org/hyades/serde/KafkaPurlDeserializer.java
  repository-meta-analyzer/src/main/java/org/hyades/serde/KafkaPurlSerde.java
  repository-meta-analyzer/src/main/java/org/hyades/serde/KafkaPurlSerializer.java
  repository-meta-analyzer/src/main/resources/application.properties
  repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerIT.java
  repository-meta-analyzer/src/test/java/org/hyades/RepositoryMetaAnalyzerTopologyTest.java
  repository-meta-analyzer/src/test/java/org/hyades/persistence/RepoEntityRepositoryTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/ComposerMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/GemMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/GoModulesMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/HexMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/MavenMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/NpmMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/NugetMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/PypiMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/hyades/repositories/RepositoryAnalyzerFactoryTest.java
  repository-meta-analyzer/src/test/java/org/hyades/serde/KafkaPurlSerdeTest.java
  vulnerability-analyzer/README.md
Labels: enhancement 🚀, domain/repo-meta-analysis 🔄

#413 Bump Redpanda and Redpanda Console
  docker-compose.yml
  mirror-service/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: enhancement 🚀, ci 🛠️

#412 Revert ID column types from int to long again
  commons/src/main/java/org/hyades/common/IConfigProperty.java
  commons/src/main/java/org/hyades/model/Component.java
  commons/src/main/java/org/hyades/model/ConfigProperty.java
  commons/src/main/java/org/hyades/model/ManagedUser.java
  commons/src/main/java/org/hyades/model/NotificationPublisher.java
  commons/src/main/java/org/hyades/model/NotificationRule.java
  commons/src/main/java/org/hyades/model/Policy.java
  commons/src/main/java/org/hyades/model/Project.java
  commons/src/main/java/org/hyades/model/Tag.java
  commons/src/main/java/org/hyades/model/Team.java
  commons/src/main/java/org/hyades/model/Vulnerability.java
  commons/src/main/java/org/hyades/model/VulnerabilityAlias.java
  commons/src/main/java/org/hyades/model/VulnerableSoftware.java
  commons/src/main/resources/migrations/postgres/V0.0.1__API-Server-4.7.0-SNAPSHOT.sql
  notification-publisher/src/test/java/org/hyades/WireMockNotificationPublisher.java
  notification-publisher/src/test/java/org/hyades/notification/NotificationRouterTest.java
  notification-publisher/src/test/java/org/hyades/persistence/ManagedUserRepositoryTest.java
  notification-publisher/src/test/java/org/hyades/persistence/TeamRepositoryTest.java
  repository-meta-analyzer/src/main/java/org/hyades/model/Repository.java
Labels: enhancement 🚀, technical debt 💸

#414 Introduce `buf` for QA of Protobuf schemas
  .github/workflows/buf.yml
  proto/src/main/proto/buf.yaml
  proto/src/main/proto/org/hyades/repometaanalysis/v1/repo_meta_analysis.proto
  proto/src/main/proto/org/hyades/vuln/v1/vuln.proto
  proto/src/main/proto/org/hyades/vulnanalysis/internal/v1beta1/vuln_analysis_internal.proto
  proto/src/main/proto/org/hyades/vulnanalysis/v1/vuln_analysis.proto
  vulnerability-analyzer/src/main/java/org/hyades/VulnerabilityAnalyzerTopology.java
  vulnerability-analyzer/src/main/java/org/hyades/client/ossindex/ModelConverter.java
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ModelConverter.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/internal/InternalScannerProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/ossindex/OssIndexProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessor.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessorConfiguration.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/snyk/SnykProcessorSupplier.java
  vulnerability-analyzer/src/main/java/org/hyades/serde/ObjectMapperCustomizer.java
  vulnerability-analyzer/src/main/java/org/hyades/serde/ProtoReflectionConfiguration.java
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerTopologyTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/internal/InternalScannerProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/ossindex/OssIndexProcessorTest.java
  vulnerability-analyzer/src/test/java/org/hyades/processor/snyk/SnykProcessorTest.java
Labels: enhancement 🚀, qa ⚖, ci 🛠️

#417 Feature/fix internal analyzer
  commons/src/main/java/org/hyades/model/Vulnerability.java
  commons/src/main/java/org/hyades/model/VulnerableSoftware.java
  commons/src/test/java/org/hyades/model/VulnerabilityTest.java
  vulnerability-analyzer/src/main/java/org/hyades/persistence/VulnerableSoftwareRepository.java
  vulnerability-analyzer/src/main/java/org/hyades/processor/internal/InternalScannerProcessor.java
Labels: bug 🐛, domain/vuln-analysis 🕵

#418 Feature/fix internal analyzer
  vulnerability-analyzer/src/test/java/org/hyades/persistence/VulnerableSoftwareRepositoryTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵, qa ⚖

#423 Fix `XPathFactoryConfigurationException` in `MavenMetaAnalyzer` when running JVM-based container image
  repository-meta-analyzer/pom.xml
Labels: bug 🐛, domain/repo-meta-analysis 🔄

#422 Initial work for end-to-end tests
  .github/workflows/e2e.yml
  README.md
  e2e/pom.xml
  e2e/src/main/java/org/hyades/apiserver/ApiServerClient.java
  e2e/src/main/java/org/hyades/apiserver/ApiServerClientHeaderFactory.java
  e2e/src/main/java/org/hyades/apiserver/model/ApiKey.java
  e2e/src/main/java/org/hyades/apiserver/model/BomProcessingResponse.java
  e2e/src/main/java/org/hyades/apiserver/model/BomUploadRequest.java
  e2e/src/main/java/org/hyades/apiserver/model/BomUploadResponse.java
  e2e/src/main/java/org/hyades/apiserver/model/ConfigProperty.java
  e2e/src/main/java/org/hyades/apiserver/model/CreateNotificationRuleRequest.java
  e2e/src/main/java/org/hyades/apiserver/model/CreateTeamRequest.java
  e2e/src/main/java/org/hyades/apiserver/model/CreateVulnerabilityRequest.java
  e2e/src/main/java/org/hyades/apiserver/model/Finding.java
  e2e/src/main/java/org/hyades/apiserver/model/NotificationPublisher.java
  e2e/src/main/java/org/hyades/apiserver/model/NotificationRule.java
  e2e/src/main/java/org/hyades/apiserver/model/Project.java
  e2e/src/main/java/org/hyades/apiserver/model/Team.java
  e2e/src/main/java/org/hyades/apiserver/model/UpdateNotificationRuleRequest.java
  e2e/src/test/java/org/hyades/e2e/AbstractE2ET.java
  e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
  e2e/src/test/resources/dtrack-apiserver-4.5.0.bom.json
  pom.xml
  scripts/create-topics.sh
Labels: enhancement 🚀, qa ⚖, ci 🛠️

#449 Run integration tests in CI workflow
  .github/workflows/ci.yml
Labels: qa ⚖, ci 🛠️

#453 Add filters to `instance` variable of Grafana dashboards
  monitoring/grafana/dashboards/mirror-service_dashboard.json
  monitoring/grafana/dashboards/notification-publisher_dashboard.json
  monitoring/grafana/dashboards/repo-meta-analyzer_dashboard.json
  monitoring/grafana/dashboards/vuln-analyzer_dashboard.json
  notification-publisher/src/main/resources/application.properties
Labels: enhancement 🚀

#448 Add tests for reworked mirror service
  mirror-service-x/pom.xml
  mirror-service-x/src/main/java/io/github/jeremylong/ghsa/GitHubSecurityAdvisoryClientBuilder.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/KafkaProducerProducer.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/AbstractDatasourceMirror.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/DatasourceMirror.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubApiClientFactory.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubConfig.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubMirror.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorConfiguration.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdApiClientFactory.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdConfig.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirror.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorConfiguration.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/state/MirrorStateStore.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/state/StateStoreUpdater.java
  mirror-service-x/src/main/java/org/hyades/vulnmirror/state/StateStores.java
  mirror-service-x/src/main/resources/application.properties
  mirror-service-x/src/test/java/org/hyades/util/WireMockTestResource.java
  mirror-service-x/src/test/java/org/hyades/vulnmirror/KafkaStreamsTopologyIT.java
  mirror-service-x/src/test/java/org/hyades/vulnmirror/TestConstants.java
  mirror-service-x/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorTest.java
  mirror-service-x/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorTest.java
  mirror-service-x/src/test/java/org/hyades/vulnmirror/state/MirrorStateStoreTest.java
  mirror-service-x/src/test/java/org/hyades/vulnmirror/state/VulnerabilityDigestStoreTest.java
  mirror-service-x/src/test/resources/datasource/github/advisories-page-01.json
  mirror-service-x/src/test/resources/datasource/github/advisories-page-02.json
  mirror-service-x/src/test/resources/datasource/github/advisory.json
  mirror-service-x/src/test/resources/datasource/nvd/cve.json
  mirror-service-x/src/test/resources/datasource/nvd/cves-page-01.json
  mirror-service-x/src/test/resources/datasource/nvd/cves-page-02.json
Labels: qa ⚖

#456 Add end-to-end tests for OSS Index and Snyk analysis
  e2e/src/main/java/org/hyades/apiserver/model/Finding.java
  e2e/src/test/java/org/hyades/e2e/BomUploadOssIndexAnalysisE2ET.java
  e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
  e2e/src/test/java/org/hyades/e2e/BomUploadSnykAnalysisE2ET.java
Labels: qa ⚖, ci 🛠️

#457 Update vuln libs to 2.0.4; Remove workarounds
  mirror-service-x/pom.xml
  mirror-service-x/src/main/java/io/github/jeremylong/ghsa/GitHubSecurityAdvisoryClientBuilder.java
  pom.xml
Labels: technical debt 💸, domain/vuln-mirroring 🪞, dependencies
