Repository DependencyTrack/hyades, pull requests merged in 2023-08, with the labels that each got.

#711 Fix native image integration tests
  .github/workflows/_build-native-meta.yml
  .github/workflows/ci.yml
  mirror-service/src/main/resources/application.properties
Labels: bug 🐛, ci 🛠️

#715 Decouple design docs from #664 into markdown file
  docs/design/01-workflow-state-tracking.md
Labels: documentation 📃

#723 Bump parallel consumer to 0.5.2.6
  notification-publisher/src/main/java/org/hyades/notification/config/ParallelConsumerConfiguration.java
  pom.xml
Labels: domain/notifications 📢, dependencies, java

#709 Add release workflow
  .github/release.yml
  .github/workflows/_build-native-meta.yml
  .github/workflows/publishJar.yml
  .github/workflows/release.yml
  commons-kstreams/pom.xml
  commons-persistence/pom.xml
  commons/pom.xml
  e2e/pom.xml
  notification-publisher/pom.xml
  pom.xml
  proto/pom.xml
  repository-meta-analyzer/pom.xml
Labels: enhancement 🚀, ci 🛠️

#726 Add IntelliJ run configurations for common tasks
  .gitignore
  .idea/icon.svg
  .idea/runConfigurations/Build.xml
  .idea/runConfigurations/Build_Container_Images.xml
  .idea/runConfigurations/Build_Native.xml
  .idea/runConfigurations/Run_E2E_Tests.xml
  .idea/runConfigurations/Run_Integration_Tests.xml
  .idea/runConfigurations/Run_Native_Integration_Tests.xml
  .idea/runConfigurations/Run_Unit_Tests.xml
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: enhancement 🚀

#729 Fix container image group not being lower-cased
  .github/workflows/publishJar.yml
  .github/workflows/release.yml
Labels: bug 🐛, ci 🛠️

#734 Remove unused `ManagedUser` class from persistence model
  commons-persistence/src/main/java/org/hyades/persistence/model/ManagedUser.java
Labels: technical debt 💸

#730 Remove unused `org.hyades.vuln.v1` proto
  proto/src/main/proto/org/hyades/vuln/v1/vuln.proto
  vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/internal/InternalScannerProcessorTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#737 Default auth required and is internal to False
  commons-persistence/src/main/java/org/hyades/persistence/model/Repository.java
  repository-meta-analyzer/src/main/java/org/hyades/processor/MetaAnalyzerProcessor.java
Labels: bug 🐛, domain/repo-meta-analysis 🔄

#739 Fix mirror task rejection causing KStreams to fail
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorConfiguration.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorConfiguration.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/osv/OsvMirrorConfiguration.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/util/LoggingRejectedExecutionHandler.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/util/LoggingUncaughtExceptionHandler.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/util/LoggingRejectedExecutionHandlerTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/util/LoggingUncaughtExceptionHandlerTest.java
Labels: bug 🐛, domain/vuln-mirroring 🪞

#744 Run e2e tests against `snapshot` tags
  e2e/src/test/java/org/hyades/e2e/AbstractE2ET.java
Labels: qa ⚖, ci 🛠️

#746 Use `dependencytrack-bot` account to push commits to `main` during release
  .github/workflows/release.yml
Labels: bug 🐛, ci 🛠️

#752 Set up documentation website with MkDocs and GitHub Pages
  .github/workflows/deploy-docs.yml
  docs/CODE_OF_CONDUCT.md
  docs/CONFIGURATION.md
  docs/CONTRIBUTING.md
  docs/DEMO.md
  docs/README.md
  docs/SECURITY.md
  docs/TOPICS.md
  docs/WTF.md
  docs/images/demo_dtrack_configure-alert.png
  docs/images/demo_dtrack_create-alert.png
  docs/images/demo_redpanda-console_consumer-groups_default-detailed.png
  docs/images/demo_redpanda-console_consumer-groups_default.png
  docs/images/demo_webhook_notifications.png
  docs/images/redpanda-console_messages.png
  docs/repository-meta-analyzer/README.md
  docs/vulnerability-analyzer/README.md
  mkdocs.yml
Labels: documentation 📃

#754 Fix vulnerability title/description mapping
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/osv/OsvMirrorTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
  mirror-service/src/test/resources/datasource/osv/GHSA-2cfc-865j-gm4w.json
  mirror-service/src/test/resources/datasource/osv/GHSA-2chv-87wj-pjv2.json
  mirror-service/src/test/resources/datasource/osv/GHSA-2cpx-6pqp-wf35.json
  vulnerability-analyzer/src/main/java/org/hyades/client/ossindex/ModelConverterToCdx.java
  vulnerability-analyzer/src/main/java/org/hyades/client/snyk/ModelConverterToCdx.java
  vulnerability-analyzer/src/test/java/org/hyades/VulnerabilityAnalyzerIT.java
  vulnerability-analyzer/src/test/java/org/hyades/client/ossindex/ModelConverterToCdxTest.java
  vulnerability-analyzer/src/test/java/org/hyades/client/snyk/ModelConverterToCdxTest.java
Labels: bug 🐛

#757 Improve BOV assertion tests for mirror-service
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
  mirror-service/src/test/resources/datasource/osv/osv-GHSA-77rv-6vfw-x4gc.json
  mirror-service/src/test/resources/datasource/osv/osv-git-commit-hash-ranges.json
  mirror-service/src/test/resources/datasource/osv/osv-vuln.json
Labels: enhancement 🚀, qa ⚖, domain/vuln-mirroring 🪞

#763 Bump Redpanda images to `v23.2.6`
  docker-compose.yml
  e2e/src/test/java/org/hyades/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: ci 🛠️

#756 Refactor NVD and OSV parsing logic to fix incorrect version range parsing
  mirror-service/pom.xml
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
  mirror-service/src/main/java/org/hyades/vulnmirror/datasource/util/ParserUtil.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/github/GitHubMirrorTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdMirrorTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/osv/OsvMirrorTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
  mirror-service/src/test/java/org/hyades/vulnmirror/datasource/util/ParserUtilTest.java
  mirror-service/src/test/resources/datasource/nvd/CVE-2017-5638-cvssv3-rating.json
  mirror-service/src/test/resources/datasource/nvd/CVE-2021-0002-duplicate-exact-version-matches.json
  mirror-service/src/test/resources/datasource/nvd/CVE-2022-31022-all-versions-vulnerable.json
  vulnerability-analyzer/src/test/java/org/hyades/processor/scanner/internal/InternalScannerProcessorTest.java
Labels: bug 🐛

#770 Enrich notification-publisher logs with context
  notification-publisher/src/main/java/org/hyades/notification/NotificationRouter.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/AbstractWebhookPublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/ConsolePublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/CsWebexPublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/DefaultNotificationPublishers.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/JiraPublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/MattermostPublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/MsTeamsPublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/PublishContext.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/Publisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/SendMailPublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/SlackPublisher.java
  notification-publisher/src/main/java/org/hyades/notification/publisher/WebhookPublisher.java
  notification-publisher/src/test/java/org/hyades/notification/NotificationRouterIT.java
  notification-publisher/src/test/java/org/hyades/notification/NotificationRouterTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/ConsolePublisherTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/CsWebexPublisherTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/DefaultNotificationPublishersTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/JiraPublisherTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/MattermostPublisherTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/MsTeamsPublisherTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/PublishContextTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/PublisherTestUtil.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/SlackPublisherTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/WebhookPublisherTest.java
Labels: enhancement 🚀, domain/notifications 📢

#775 Fix breaking change in `NEW_VULNERABILITY` notification JSON format
  e2e/src/main/java/org/hyades/apiserver/model/CreateVulnerabilityRequest.java
  e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
  notification-publisher/src/test/java/org/hyades/notification/NotificationRouterTest.java
  notification-publisher/src/test/java/org/hyades/notification/publisher/WebhookPublisherTest.java
  proto/src/main/proto/org/hyades/notification/v1/notification.proto
Labels: bug 🐛

#777 Fix broken decimal comparison in `BomUploadProcessingE2ET`
  e2e/src/test/java/org/hyades/e2e/BomUploadProcessingE2ET.java
Labels: qa ⚖
