Repository DependencyTrack/hyades, pull requests merged in 2024-06, with the labels that each got.

#1293 Update schema for clone project workflow
  commons-persistence/src/main/resources/schema.sql
Labels: enhancement

#1285 Remove `generate-cwe-definitions.py`
  commons/src/main/java/org/dependencytrack/common/cwe/CweDefinitions.java
  commons/src/main/java/org/dependencytrack/common/cwe/CweDictionary.java
  commons/src/main/java/org/dependencytrack/common/cwe/CweResolver.java
  scripts/generate-cwe-definitions.py
Labels: technical debt

#1250 Add mode of operation in Vulnerability policy
  commons-persistence/src/main/resources/schema.sql
Labels: enhancement

#1303 Add CVSS and OWASP vectors to notification proto
  proto/src/main/proto/org/dependencytrack/notification/v1/notification.proto
Labels: enhancement

#1304 Fix `VulnerabilityPolicyE2ET`
  e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Labels: defect, qa

#1305 Port: withdrawn check for github advisory
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirror.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirrorTest.java
  mirror-service/src/test/resources/datasource/github/advisory-withdrawn.json
Labels: defect, v4-port

#1307 Port: Configurable email subject prefix
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisherConfig.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
Labels: enhancement, v4-port

#1309 Port fix for npm purls with special characters
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/AbstractMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NpmMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NpmMetaAnalyzerTest.java
Labels: defect, v4-port

#1310 Add docs for advanced database config
  docs/operations/database.md
  mkdocs.yml
Labels: documentation

#1308 Fix CVSS vectors missing from e2e notification asserts
  e2e/src/test/java/org/dependencytrack/e2e/BomProcessedNotificationDelayedE2ET.java
  e2e/src/test/java/org/dependencytrack/e2e/BomUploadProcessingE2ET.java
  e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Labels: defect, qa

#1313 Bump Redpanda and Redpanda Console
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies, docker

#1191 Add initial development docs
  DEVELOPING.md
  docs/development/building.md
  docs/development/database-migrations.md
  docs/development/documentation.md
  docs/development/overview.md
  docs/development/testing.md
  docs/images/dev_docs_config-deeplink.png
  docs/images/dev_docs_versions.png
  mkdocs.yml
Labels: documentation

#1321 Fix `role "root" does not exist` in postgres healthcheck
  docker-compose.yml
Labels: defect

#1322 Port: Bump CWE dictionary to v4.13
  commons/src/main/java/org/dependencytrack/common/cwe/CweDictionary.java
Labels: enhancement, v4-port

#1323 Schema change to add component property
  commons-persistence/src/main/resources/schema.sql
Labels: enhancement

#1314 Port: Fix Slack notifications failing when no base URL is configured + Add tests for `NewVulnerableDependencySubject`
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherWithoutBaseUrlTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
  notification-publisher/src/test/resources/templates/email.peb
  notification-publisher/src/test/resources/templates/jira.peb
  notification-publisher/src/test/resources/templates/msteams.peb
  notification-publisher/src/test/resources/templates/slack.peb
Labels: defect, v4-port

#1325 Update Deployment docs for Helm chart
  README.md
Labels: documentation

#1330 Port: Disable Maven transfer progress in CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: dx, v4-port

#1332 Port: add hackage and nixpkgs analyzers
  .gitignore
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/RepositoryType.java
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/HackageMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NixpkgsMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/HackageMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NixpkgsMetaAnalyzerTest.java
Labels: enhancement, v4-port

#1315 Decouple e2e tests into separate workflow
  .github/workflows/e2e-test.yml
  .github/workflows/publishJar.yml
  DEVELOPING.md
  docs/development/testing.md
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
Labels: qa, ci

#1334 Fix e2e tests failing to get API keys
  e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
Labels: defect, qa

#1331 Link to docs for DB migration and doc update checkboxes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1348 Update port status in `README.md`
  README.md
Labels: documentation

#1344 Update schema for Component Property
  commons-persistence/src/main/resources/schema.sql
Labels: enhancement

#1353 Remove Helm chart
  .github/workflows/helm-ci.yml
  helm-charts/hyades/Chart.yaml
  helm-charts/hyades/README.md
  helm-charts/hyades/templates/_helpers.tpl
  helm-charts/hyades/templates/api-server/deployment.yaml
  helm-charts/hyades/templates/api-server/ingress.yaml
  helm-charts/hyades/templates/api-server/service.yaml
  helm-charts/hyades/templates/api-server/servicemonitor.yaml
  helm-charts/hyades/templates/frontend/deployment.yaml
  helm-charts/hyades/templates/frontend/ingress.yaml
  helm-charts/hyades/templates/frontend/service.yaml
  helm-charts/hyades/templates/mirror-service/deployment.yaml
  helm-charts/hyades/templates/notification-publisher/deployment.yaml
  helm-charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  helm-charts/hyades/templates/secret.yaml
  helm-charts/hyades/templates/vuln-analyzer/service.yaml
  helm-charts/hyades/templates/vuln-analyzer/statefulset.yaml
  helm-charts/hyades/values-minikube.yaml
  helm-charts/hyades/values.yaml
Labels: technical debt
