Repository DependencyTrack/hyades, pull requests merged in 2024-05, with the labels that each got.

#1229 Pull config via `@ConfigProperty` in notification-publisher
  commons-persistence/src/main/java/org/dependencytrack/persistence/converter/PropertyTypeConverter.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/ConfigProperty.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/ConfigPropertyConstants.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/IConfigProperty.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/repository/ConfigPropertyRepository.java
  commons-persistence/src/test/java/org/dependencytrack/persistence/converter/PropertyTypeConverter.java
  commons-persistence/src/test/java/org/dependencytrack/persistence/converter/PropertyTypeConverterTest.java
  commons-persistence/src/test/java/org/dependencytrack/persistence/repository/ConfigPropertyRepositoryTest.java
  docs/reference/configuration/overview.md
  notification-publisher/pom.xml
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/ConsolePublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/CsWebexPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/JiraPublisherConfig.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/MattermostPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/MsTeamsPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/Publisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisherConfig.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SlackPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/WebhookPublisher.java
  notification-publisher/src/main/resources/application.properties
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherBearerTokenTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
  pom.xml
Labels: enhancement, domain/notifications

#1254 Introduce quarkus wiremock extension
  commons/pom.xml
  commons/src/test/java/org/dependencytrack/common/HttpClientTests.java
  commons/src/test/java/org/dependencytrack/util/WireMockTestResource.java
  mirror-service/pom.xml
  mirror-service/src/test/java/org/dependencytrack/repometaanalyzer/util/WireMockTestResource.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/KafkaStreamsTopologyIT.java
  notification-publisher/pom.xml
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterIT.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherBearerTokenTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/util/WireMockTestResource.java
  pom.xml
  repository-meta-analyzer/pom.xml
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/RepositoryMetaAnalyzerIT.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/util/WireMockTestResource.java
  vulnerability-analyzer/pom.xml
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/VulnerabilityAnalyzerIT.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/snyk/SnykClientTest.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/util/WireMockTestResource.java
Labels: technical debt

#1264 Add date format to support offset in nuget analyser
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzerTest.java
Labels: defect

#1266 Fix broken email notifications in e2e test
  e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  e2e/src/test/java/org/dependencytrack/e2e/BomUploadProcessingE2ET.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
Labels: defect, qa

#1235 Change Sonar to Codacy
  .github/workflows/ci-test-pr-coverage.yml
  .github/workflows/ci.yml
  commons/src/test/java/org/dependencytrack/commonutil/DateUtilTest.java
Labels: ci

#1273 Fix parsing of decimal numbers in non-English locales
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdx.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java
Labels: defect

#1275 Fix `Publish test coverage` build step
  .github/workflows/ci.yml
Labels: ci

#1277 Fix `Commit SHA-1 hash isn't valid` when publishing coverage
  .github/workflows/ci.yml
Labels: ci

#1280 Minor doc fixes
  docs/operations/database.md
  docs/reference/configuration/api-server.md
  docs/reference/configuration/mirror-service.md
  scripts/config-docs.md.peb
Labels: documentation

#1281 Remove Sonar properties
  pom.xml
Labels: documentation

#1283 Bump `cvss-calculator` to `1.4.3`
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
  pom.xml
  repository-meta-analyzer/pom.xml
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdx.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/VulnerabilityAnalyzerIT.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdxTest.java
Labels: dependencies, java

#1284 Move `GenerateConfigDocs` to `DependencyTrack/jbang-catalog`
  .github/workflows/update-config-docs.yml
  DEVELOPING.md
  scripts/GenerateConfigDocs.java
Labels: technical debt, ci

#1286 Enrich repo-meta-analyzer configuration with annotations for docs generation
  .github/workflows/update-config-docs.yml
  docs/reference/configuration/repo-meta-analyzer.md
  mirror-service/src/main/resources/application.properties
  mkdocs.yml
  repository-meta-analyzer/src/main/resources/application.properties
Labels: documentation

#1298 Fix inconsistent `source` identifier for GitHub Advisories
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
Labels: defect
