Repository DependencyTrack/hyades, pull requests merged in 2024-07, with the labels that each got.

#1354 Clean up and extend documentation
  .github/images/demo_dtrack_configure-alert.png
  .github/images/demo_dtrack_create-alert.png
  .github/images/demo_redpanda-console_consumer-groups_default-detailed.png
  .github/images/demo_redpanda-console_consumer-groups_default.png
  .github/images/demo_webhook_notifications.png
  .github/images/redpanda-console_messages.png
  CONTRIBUTING.md
  DEVELOPING.md
  WTF.md
  docs/README.md
  docs/about.md
  docs/architecture/design/workflow-state-tracking.md
  docs/architecture/index.md
  docs/architecture/overview.md
  docs/development/database-migrations.md
  docs/development/overview.md
  docs/development/testing.md
  docs/getting-started/changes-over-v4.md
  docs/getting-started/migrating-from-v4.md
  docs/images/dependencytrack-executorservice.png
  docs/images/getting-started/migrating-from-v4_bento-api-key.png
  docs/images/getting-started/migrating-from-v4_configure-alert.png
  docs/images/getting-started/migrating-from-v4_create-alert.png
  docs/images/hyades-star-cluster.png
  docs/index.md
  docs/operations/database.md
  docs/usage/policy-bundle-example/test.zip
  docs/usage/policy-compliance/expressions.md
  mkdocs.yml
Labels: documentation

#1367 Enable social cards for documentation
  .github/workflows/deploy-docs.yml
  .gitignore
  mkdocs.yml
Labels: documentation

#1388 Gracefully handle `MalformedVectorException`s for invalid CVSS vectors
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdx.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdxTest.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdxTest.java
Labels: defect

#1382 Update CDX schema to v1.6
  docker-compose.yml
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/AbstractDatasourceMirror.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirror.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdMirror.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvMirror.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/dto/OsvDto.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/util/ParserUtil.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/KafkaStreamsTopologyIT.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirrorTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdMirrorTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/osv/OsvMirrorTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/util/ParserUtilTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/state/VulnerabilityDigestStoreTest.java
  proto/src/main/proto/buf.yaml
  proto/src/main/proto/org/cyclonedx/v1_4/cyclonedx.proto
  proto/src/main/proto/org/cyclonedx/v1_6/cyclonedx.proto
  proto/src/main/proto/org/dependencytrack/vulnanalysis/v1/vuln_analysis.proto
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdx.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/Report.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/snyk/SnykProcessor.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/VulnerabilityAnalyzerIT.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/ossindex/ModelConverterToCdxTest.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdxTest.java
Labels: enhancement

#1399 Fix max.compaction.lag.ms to make it compatible with Apache Kafka
  commons-kstreams/src/main/java/org/dependencytrack/kstreams/statestore/StateStoreUtil.java
  commons-kstreams/src/test/java/org/dependencytrack/kstreams/statestore/StateStoreUtilTest.java
  docs/reference/topics.md
  scripts/create-topics.sh
Labels: defect

#1398 Bump Redpanda to v24.1.11
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies, docker

#1411 Rename kafka topic prefix for apache kafka compatibility
  commons/src/main/java/org/dependencytrack/common/KafkaTopic.java
  commons/src/test/java/org/dependencytrack/common/KafkaTopicTest.java
  docs/reference/configuration/api-server.md
  docs/reference/configuration/mirror-service.md
  docs/reference/configuration/overview.md
  docs/reference/configuration/repo-meta-analyzer.md
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/java/org/dependencytrack/notification/config/ParallelConsumerConfiguration.java
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  scripts/create-topics.sh
  vulnerability-analyzer/src/main/resources/application.properties
Labels: defect, breaking change

#1414 Add breaking changes category to release notes
  .github/release.yml
Labels: documentation
