Repository DependencyTrack/hyades, pull requests merged in 2024-09, with the labels that each got.

#1479 Add initializer container to Docker Compose
  docker-compose.yml
Labels: enhancement

#1489 Update architecture diagram to mark API server as scalable
  docs/architecture-overview.drawio
  docs/architecture-overview.png
Labels: documentation

#1490 Add upgrade notes
  docs/getting-started/upgrading.md
  mkdocs.yml
Labels: documentation

#1492 Docs: integrate TOC into navigation bar for more content space
  mkdocs.yml
Labels: documentation

#1496 Disable database connection pooling for initializer
  docker-compose.yml
Labels: enhancement

#1498 Limit memory usage of RocksDB and make it more configurable
  commons-kstreams/src/main/java/org/dependencytrack/kstreams/statestore/RocksDbConfigSetter.java
  commons-kstreams/src/main/java/org/dependencytrack/kstreams/statestore/StateStoreConfig.java
  commons-kstreams/src/test/java/org/dependencytrack/kstreams/statestore/RocksDbConfigSetterTest.java
  vulnerability-analyzer/src/main/resources/application.properties
Labels: enhancement

#1502 Migrate to Quarkus-native CycloneDX SBOM generation
  .github/workflows/release.yml
  mirror-service/pom.xml
  notification-publisher/pom.xml
  pom.xml
  repository-meta-analyzer/pom.xml
  vulnerability-analyzer/pom.xml
Labels: enhancement

#1503 Add upgrade note for Kafka processor property name change
  docs/getting-started/upgrading.md
Labels: documentation

#1511 Remove deprecated code + update documentation
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Vulnerability.java
  docs/getting-started/changes-over-v4.md
  docs/getting-started/upgrading.md
Labels: technical debt

#1516 Update `schema.sql` for `JSONB` migration of `DIRECT_DEPENDENCIES`
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Project.java
  commons-persistence/src/main/resources/schema.sql
Labels: enhancement

#1518 Fix native `mirror-service` not being built upon change in `commons-persistence`
  .github/workflows/build-native-mirror-service.yml
Labels: defect

#1529 Enable `reWriteBatchedInserts` Postgres JDBC driver option in e2e tests
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
Labels: enhancement

#1530 Fix scheduled e2e tests failing due to missing image tag
  .github/workflows/e2e-test.yml
Labels: defect

#1532 Port : Add tag support for notifications
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationRule.java
  commons-persistence/src/main/resources/schema.sql
  commons-persistence/src/test/java/org/dependencytrack/persistence/model/NotificationRuleTest.java
  notification-publisher/src/main/java/org/dependencytrack/notification/NotificationRouter.java
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: enhancement, v4-port

#1537 Add initializer container to e2e tests
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
Labels: enhancement
