Repository DependencyTrack/hyades, pull requests merged in 2024-04, with the labels that each got.

#1165 Load cluster ID from database on startup
  commons-persistence/src/main/java/org/dependencytrack/persistence/ClusterInfoProducer.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/ConfigPropertyConstants.java
  commons-persistence/src/main/resources/schema.sql
  commons-persistence/src/test/java/org/dependencytrack/persistence/repository/ConfigPropertyRepositoryTest.java
  commons/src/main/java/org/dependencytrack/common/ClusterInfo.java
  commons/src/main/java/org/dependencytrack/common/ClusterInfoProducer.java
  commons/src/main/java/org/dependencytrack/common/HttpClientConfiguration.java
  commons/src/main/java/org/dependencytrack/common/UserAgent.java
  commons/src/main/java/org/dependencytrack/common/UserAgentProducer.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/ossindex/AuthorizationClientHeaderFactory.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/AuthorizationClientHeaderFactory.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/ossindex/AuthorizationClientHeaderFactoryTest.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/client/snyk/AuthorizationClientHeaderFactoryTest.java
Labels: enhancement 🚀

#1168 Handle duplicate issues reported by Snyk
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/processor/scanner/snyk/SnykProcessorTest.java
  vulnerability-analyzer/src/test/resources/snyk/duplicate-issues-response.json
Labels: enhancement 🚀, domain/vuln-analysis 🕵

#1173 Use `/dev/urandom` instead of `openssl rand` to generate secret key
  docker-compose.yml
Labels: enhancement 🚀

#1170 Fix broken e2e tests due to Quarkus RestClient requiring CDI context
  e2e/pom.xml
  e2e/src/main/java/org/dependencytrack/apiserver/ApiServerAuthInterceptor.java
  e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
  e2e/src/main/java/org/dependencytrack/apiserver/CompositeDecoder.java
  e2e/src/main/java/org/dependencytrack/apiserver/CompositeEncoder.java
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  pom.xml
Labels: bug 🐛, qa ⚖

#1176 Setup GitHub issue and PR templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/defect-report.yml
  .github/ISSUE_TEMPLATE/enhancement-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation 📃

#1178 Fix broken assertion in e2e test
  e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Labels: qa ⚖

#1182 De-duplicate Snyk vulnerabilities by ID
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/client/snyk/ModelConverterToCdx.java
Labels: bug 🐛, domain/vuln-analysis 🕵

#1180 Fix mapping of CPEs to vers ranges when version is NA (`-`)
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
  mirror-service/src/test/resources/datasource/nvd/cve-vuln.json
  pom.xml
Labels: bug 🐛

#1093 Update API server dashboard to use Parallel Consumer metric for mirror processing duration
  monitoring/grafana/dashboards/apiserver_dashboard.json
Labels: api-server 🏰, observability

#1094 Update API server dashboard to include Parallel Consumer metric for repo meta processing duration
  monitoring/grafana/dashboards/apiserver_dashboard.json
Labels: api-server 🏰, observability

#1187 Bump `kafka-clients` to 3.6.2 and remove `mockserver-netty`
  notification-publisher/pom.xml
  pom.xml
Labels: dependencies, java

#1186 Bump images
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies, docker

#1194 Add database operations documentation
  docs/images/operations_database_pgtune.png
  docs/operations/database.md
  mkdocs.yml
Labels: documentation 📃

#1156 Add script to generate config docs
  .github/workflows/update-config-docs.yml
  DEVELOPING.md
  docs/reference/configuration/api-server.md
  docs/reference/configuration/overview.md
  mkdocs.yml
  scripts/GenerateConfigDocs.java
  scripts/config-docs.md.peb
Labels: documentation 📃

#1198 Doc: Schema present mssql as possible database
  docs/architecture-overview.drawio
  docs/architecture-overview.png
  docs/reference/configuration/api-server.md
Labels: documentation 📃

#1199 Remove timestamp from config doc template
  scripts/config-docs.md.peb
Labels: documentation 📃

#1204 Don't label docs for `SNAPSHOT` versions as `latest`
  .github/workflows/deploy-docs.yml
Labels: documentation 📃

#1206 Enrich mirror-service configuration with annotations for docs generation
  docs/reference/configuration/mirror-service.md
  mirror-service/src/main/resources/application.properties
  mkdocs.yml
Labels: documentation 📃

#1209 Alias docs for `-SNAPSHOT` versions as `snapshot`
  .github/workflows/deploy-docs.yml
Labels: documentation 📃

#1211 Use hyperlinks when referring to configuration options in the docs
  docs/operations/database.md
Labels: documentation 📃

#1225 Wrap jdbc url environment variables in with conditional
  helm-charts/hyades/Chart.yaml
  helm-charts/hyades/README.md
  helm-charts/hyades/templates/api-server/deployment.yaml
  helm-charts/hyades/templates/notification-publisher/deployment.yaml
  helm-charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  helm-charts/hyades/templates/vuln-analyzer/statefulset.yaml
Labels: enhancement 🚀, deployment 🏗

#1212 Issue 947 : Add table vulnerability_tags in schema
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Tag.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Vulnerability.java
  commons-persistence/src/main/resources/schema.sql
  commons-persistence/src/test/java/org/dependencytrack/persistence/model/TagTest.java
  commons-persistence/src/test/java/org/dependencytrack/persistence/model/VulnerabilityTest.java
Labels: enhancement

#1239 Update labels used in workflows and release notes
  .github/release.yml
  .github/workflows/update-config-docs.yml
Labels: meta

#1193 Display percentiles for event processing durations on Grafana dashboard
  monitoring/grafana/dashboards/apiserver_dashboard.json
Labels: enhancement, observability

#1245 POM cleanup
  mirror-service/pom.xml
  notification-publisher/pom.xml
  pom.xml
  repository-meta-analyzer/pom.xml
  vulnerability-analyzer/pom.xml
Labels: technical debt

#1246 Fix Checkstyle error when running specific Maven module
  .checkstyle.xml
  pom.xml
Labels: dx

#1242 porting issue-3511 adding cargo analyzer
  commons/pom.xml
  commons/src/main/java/org/dependencytrack/commonutil/DateUtil.java
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/CargoMetaAnalyzer.java
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/RepositoryAnalyzerFactory.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/CargoMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/RepositoryAnalyzerFactoryTest.java
Labels: port

#1248 Bump Redpanda containers
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies, docker
