Repository DependencyTrack/hyades, pull requests merged in 2024-02, with the labels that each got.

#1051 Backport minor bug fixes
  notification-publisher/src/main/java/org/dependencytrack/notification/NotificationRouter.java
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/GithubMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GitHubMetaAnalyzerTest.java
Labels: bug 🐛

#1060 Fix Hibernate exception due to `null` being assigned to primitive `boolean`
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationRule.java
Labels: bug 🐛, domain/notifications 📢

#1065 Improve Docker Compose setup
  DEMO.md
  README.md
  docker-compose.yml
  docs/DEMO.md
Labels: documentation 📃, enhancement 🚀

#1067 Add some simple helper scripts
  scripts/change-user-pass.sh
  scripts/upload-boms.sh
Labels: enhancement 🚀

#1061 Fix false positives in CPE matching due to ambiguous vendor/product relations
  commons-persistence/src/main/java/org/dependencytrack/persistence/repository/VulnerableSoftwareRepository.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/internal/InternalScannerProcessor.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/processor/scanner/internal/InternalScannerProcessorTest.java
Labels: bug 🐛, domain/vuln-analysis 🕵

#1073 Port notification publisher fixes and tests
  notification-publisher/pom.xml
  notification-publisher/src/main/java/org/dependencytrack/notification/NotificationConstants.java
  notification-publisher/src/main/java/org/dependencytrack/notification/config/PebbleConfiguration.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/ConsolePublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/CsWebexPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/MattermostPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/MsTeamsPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/Publisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SlackPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/WebhookPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/template/extension/CustomExtension.java
  notification-publisher/src/main/java/org/dependencytrack/notification/template/extension/SummarizeFilter.java
  notification-publisher/src/main/resources/application.properties
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
  notification-publisher/src/test/resources/templates/console.peb
  notification-publisher/src/test/resources/templates/cswebex.peb
  notification-publisher/src/test/resources/templates/email.peb
  notification-publisher/src/test/resources/templates/jira.peb
  notification-publisher/src/test/resources/templates/mattermost.peb
  notification-publisher/src/test/resources/templates/msteams.peb
  notification-publisher/src/test/resources/templates/slack.peb
  notification-publisher/src/test/resources/templates/webhook.peb
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: bug 🐛, domain/notifications 📢, qa ⚖

#1081 Rename kafka topic prefix config
  commons/src/main/java/org/dependencytrack/common/KafkaTopic.java
  commons/src/test/java/org/dependencytrack/common/KafkaTopicTest.java
  docker-compose.yml
  docs/reference/configuration.md
  helm-charts/hyades/templates/api-server/deployment.yaml
  helm-charts/hyades/templates/mirror-service/deployment.yaml
  helm-charts/hyades/templates/notification-publisher/deployment.yaml
  helm-charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  helm-charts/hyades/templates/vuln-analyzer/statefulset.yaml
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/java/org/dependencytrack/notification/config/ParallelConsumerConfiguration.java
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  scripts/create-topics.sh
  vulnerability-analyzer/src/main/resources/application.properties
Labels: technical debt 💸

#1089 Bump Redpanda and Redpanda Console
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies, docker

#1104 Don't assert order of findings returned by REST API in e2e test
  e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Labels: qa ⚖

#1102 Emit logs as `WARN` when encountering retryable exceptions
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/retry/RetryableRecord.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/ossindex/OssIndexProcessor.java
  vulnerability-analyzer/src/main/java/org/dependencytrack/vulnanalyzer/processor/scanner/snyk/SnykProcessor.java
  vulnerability-analyzer/src/test/java/org/dependencytrack/vulnanalyzer/processor/retry/RetryableRecordTest.java
Labels: enhancement 🚀, domain/vuln-analysis 🕵, observability

#1109 Fix `generate-bom-testdata.sh` failing due to removed ZAP image
  scripts/generate-bom-testdata.sh
  testdata/boms/generated/README.md
  testdata/boms/generated/images.txt
Labels: bug 🐛

#1095 Bump container base images to Java 21, and build against Java 21 in CI
  .github/workflows/_build-native-meta.yml
  .github/workflows/ci.yml
  .github/workflows/publishJar.yml
  .github/workflows/release.yml
  mirror-service/src/main/docker/Dockerfile.jvm
  notification-publisher/src/main/docker/Dockerfile.jvm
  repository-meta-analyzer/src/main/docker/Dockerfile.jvm
  vulnerability-analyzer/src/main/docker/Dockerfile.jvm
Labels: enhancement 🚀, ci 🛠️
