Repository DependencyTrack/hyades, pull requests merged in 2024-11, with the labels that each got.

#1595 Port : Exclude pre-releases from NuGet latest version check
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzerTest.java
Labels: enhancement, v4-port

#1602 Bump various containers tags
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies

#1596 Fix missing reflection configs for NVD model classes
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdReflectionConfiguration.java
Labels: defect
