Repository DependencyTrack/hyades, pull requests merged in 2024-03, with the labels that each got.

#1119 removed usage of mockserver
  commons/pom.xml
  commons/src/test/java/org/dependencytrack/common/HttpClientTests.java
  commons/src/test/java/org/dependencytrack/util/WireMockTestResource.java
  repository-meta-analyzer/pom.xml
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/RepositoryMetaAnalyzerIT.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/processor/MetaAnalyzerProcessorTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/ComposerMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/CpanMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GemMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GoModulesMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/HexMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/MavenMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NpmMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/NugetMetaAnalyzerTest.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/PypiMetaAnalyzerTest.java
Labels: technical debt 💸

#1114 Synchronize DB schema with API server
  commons-persistence/src/main/resources/schema.sql
Labels: qa ⚖

#1144 Reduce verbosity of Maven in CI
  .github/workflows/_build-native-meta.yml
  .github/workflows/ci.yml
  .github/workflows/publishJar.yml
  .github/workflows/release.yml
Labels: ci 🛠️

#1098 Raise baseline Java version to 21
  README.md
  pom.xml
Labels: enhancement 🚀

#1103 Replace custom vers handling with versatile
  mirror-service/pom.xml
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirrorTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/osv/OsvMirrorTest.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParserTest.java
  pom.xml
Labels: technical debt 💸
