Repository DependencyTrack/hyades, pull requests merged in 2024-01, with the labels that each got.

#1001 Fix `repometaanalyzer` package being used in notification-publisher module
  notification-publisher/src/main/java/org/dependencytrack/notification/NotificationRouter.java
  notification-publisher/src/main/java/org/dependencytrack/notification/config/ParallelConsumerConfiguration.java
  notification-publisher/src/main/java/org/dependencytrack/notification/health/ParallelConsumerHealthCheck.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/util/ModelConverter.java
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterIT.java
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/util/ModelConverterTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/util/WireMockTestResource.java
Labels: technical debt 💸

#1036 Bump Redpanda to v23.3.3
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies

#1035 Remove `CEL_POLICY_ENGINE_ENABLED` from `docker-compose.yml`
  docker-compose.yml
Labels: technical debt 💸

#1040 Bump Redpanda Console to v2.4.0
  docker-compose.yml
Labels: dependencies

#1041 Use Mandrel 23.1 to build native images
  .github/workflows/_build-native-meta.yml
Labels: ci 🛠️, dependencies, native-image

#1042 Fix broken native build caused by Cloud SQL socket factory
  .github/workflows/_build-native-meta.yml
  .github/workflows/ci.yml
  .idea/runConfigurations/Build_Native.xml
  .idea/runConfigurations/Run_Native_Integration_Tests.xml
  commons-persistence/pom.xml
  mirror-service/pom.xml
  notification-publisher/pom.xml
  pom.xml
  repository-meta-analyzer/pom.xml
  vulnerability-analyzer/pom.xml
Labels: bug 🐛, ci 🛠️, native-image

#1032 Add support for github meta analyzer
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/RepositoryType.java
  commons-persistence/src/test/java/org/dependencytrack/persistence/model/RepositoryTypeTest.java
  repository-meta-analyzer/pom.xml
  repository-meta-analyzer/src/main/java/org/dependencytrack/repometaanalyzer/repositories/GithubMetaAnalyzer.java
  repository-meta-analyzer/src/test/java/org/dependencytrack/repometaanalyzer/repositories/GitHubMetaAnalyzerTest.java
Labels: enhancement 🚀

#1043 Tweak Kafka Streams config
  mirror-service/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: enhancement 🚀

#1012 Incorporate manual sync trigger in vuln policy e2e test
  e2e/src/main/java/org/dependencytrack/apiserver/ApiServerClient.java
  e2e/src/main/java/org/dependencytrack/apiserver/model/WorkflowTokenResponse.java
  e2e/src/test/java/org/dependencytrack/e2e/BomProcessedNotificationDelayedE2ET.java
  e2e/src/test/java/org/dependencytrack/e2e/BomUploadOssIndexAnalysisE2ET.java
  e2e/src/test/java/org/dependencytrack/e2e/BomUploadProcessingE2ET.java
  e2e/src/test/java/org/dependencytrack/e2e/BomUploadSnykAnalysisE2ET.java
  e2e/src/test/java/org/dependencytrack/e2e/VulnerabilityPolicyE2ET.java
Labels: qa ⚖

#1048 Use macOS M1 runner to build arm64 binaries
  .github/workflows/_build-native-meta.yml
Labels: ci 🛠️, native-image

#1049 Revert "Use macOS M1 runner to build arm64 binaries"
  .github/workflows/_build-native-meta.yml
Labels: ci 🛠️, native-image
