Repository DependencyTrack/hyades, pull requests merged in 2024-08, with the labels that each got.

#1429 Update various dependencies
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  pom.xml
  repository-meta-analyzer/pom.xml
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies, docker, java

#1433 Enable Quarkus incubating model resolver
  .mvn/maven.config
Labels: enhancement

#1441 Bump Redpanda to v24.2.2
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies, docker

#1440 Port : Fix project link for new vulnerable dependency for email
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  notification-publisher/src/test/resources/templates/email.peb
Labels: defect, v4-port

#1445 Port: Bump CWE dictionary to v4.14
  commons/src/main/java/org/dependencytrack/common/cwe/CweDictionary.java
Labels: enhancement

#1443 Port : Add Notification For `BOM_VALIDATION_FAILED`
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationGroup.java
  docs/reference/schemas/notification.md
  notification-publisher/src/main/java/org/dependencytrack/notification/NotificationConstants.java
  notification-publisher/src/main/java/org/dependencytrack/notification/NotificationRouter.java
  notification-publisher/src/main/java/org/dependencytrack/notification/config/ProtoReflectionConfiguration.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/PublishContext.java
  notification-publisher/src/main/java/org/dependencytrack/notification/publisher/Publisher.java
  notification-publisher/src/main/java/org/dependencytrack/notification/util/ModelConverter.java
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/PublishContextTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
  notification-publisher/src/test/resources/templates/email.peb
  notification-publisher/src/test/resources/templates/msteams.peb
  notification-publisher/src/test/resources/templates/slack.peb
  proto/src/main/proto/org/dependencytrack/notification/v1/notification.proto
Labels: enhancement, v4-port

#1460 Add build instructions to development docs
  docs/development/building.md
Labels: documentation

#1452 Use native `UUID` type for UUID colums
  commons-persistence/src/main/java/org/dependencytrack/persistence/converter/UUIDConverter.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Component.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationPublisher.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationRule.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Project.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Repository.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Vulnerability.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/VulnerabilityAlias.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/VulnerableSoftware.java
  commons-persistence/src/main/resources/schema.sql
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: enhancement, performance

#1467 Revert "Revert "Use native `UUID` type for UUID colums""
  commons-persistence/src/main/java/org/dependencytrack/persistence/converter/UUIDConverter.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Component.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationPublisher.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/NotificationRule.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Project.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Repository.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Vulnerability.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/VulnerabilityAlias.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/VulnerableSoftware.java
  commons-persistence/src/main/resources/schema.sql
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: enhancement
