Repository DependencyTrack/hyades, pull requests merged in 2025-01, with the labels that each got.

#1611 Migrate project `active` flag to date type `inactiveSince`
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Project.java
  commons-persistence/src/main/resources/schema.sql
  notification-publisher/src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: enhancement

#1623 Replace `github-api` with `quarkus-github-api` extension
  pom.xml
  repository-meta-analyzer/pom.xml
Labels: dependencies

#1631 Port : Fix CPE matching for NVD mirroring via REST API
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParserTest.java
  mirror-service/src/test/resources/datasource/nvd/cve-2024-23113.json
Labels: defect, domain/vuln-mirroring, v4-port

#1635 Bump Quarkus to 3.17.8
  pom.xml
Labels: dependencies

#1644 Apply missing migration changesets to `schema.sql`
  commons-persistence/src/main/resources/schema.sql
Labels: technical debt

#1649 Port: Handle GitHub GraphQL API rate limiting
  mirror-service/pom.xml
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubApiClientFactory.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubHttpRequestRetryStrategy.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubMirror.java
  mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubReflectionConfiguration.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/KafkaStreamsTopologyIT.java
  mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubHttpRequestRetryStrategyTest.java
  mirror-service/src/test/resources/datasource/github/advisories-page-01.json
  mirror-service/src/test/resources/datasource/github/advisories-page-02.json
  mirror-service/src/test/resources/datasource/github/advisory-02.json
  mirror-service/src/test/resources/datasource/github/advisory-withdrawn.json
  mirror-service/src/test/resources/datasource/github/advisory.json
  pom.xml
Labels: defect, v4-port
