Repository DependencyTrack/hyades, pull requests merged in 2025-03, with the labels that each got.

#1692 Update ADR-004 to include file media type and SHA-256 digest
  docs/architecture/decisions/004-file-storage-plugin.md
Labels: documentation

#1715 Fix typo in the README
  README.md
Labels: documentation

#1714 Issue-1090 : Document Findings response changes.
  docs/getting-started/changes-over-v4.md
Labels: documentation

#1700 Materialize project hierarchies in separate table
  commons-persistence/src/main/java/org/dependencytrack/persistence/model/Project.java
  commons-persistence/src/main/java/org/dependencytrack/persistence/repository/ProjectRepository.java
  commons-persistence/src/main/resources/schema.sql
  commons-persistence/src/test/java/org/dependencytrack/persistence/repository/ProjectRepositoryTest.java
  docs/architecture/decisions/005-materialize-project-hierarchies.md
  mkdocs.yml
  notification-publisher/src/main/java/org/dependencytrack/notification/NotificationRouter.java
Labels: enhancement

#1727 Raise minimum supported PostgreSQL version to 13
  commons-persistence/src/test/resources/application.properties
  docs/getting-started/upgrading.md
  docs/operations/database.md
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: technical debt
