Repository DependencyTrack/hyades, pull requests merged in 2025-02, with the labels that each got.

#1619 Add ADRs for dropping dependency on Kafka
  docs/architecture/decisions/000-index.md
  docs/architecture/decisions/001-drop-kafka-dependency.md
  docs/architecture/decisions/002-workflow-orchestration.md
  docs/architecture/decisions/003-notification-publishing.md
  docs/architecture/decisions/004-file-storage-plugin.md
  mkdocs.yml
Labels: documentation, proposal, architecture

#1662 Use native ARM runner to build arm64 native images
  .github/workflows/_build-native-meta.yml
Labels: ci

#1664 Remove buildx from native image build job
  .github/workflows/_build-native-meta.yml
Labels: defect, ci

#1669 Bump container image versions
  docker-compose.yml
  e2e/src/test/java/org/dependencytrack/e2e/AbstractE2ET.java
  mirror-service/src/main/resources/application.properties
  notification-publisher/src/main/resources/application.properties
  repository-meta-analyzer/src/main/resources/application.properties
  vulnerability-analyzer/src/main/resources/application.properties
Labels: dependencies

#1673 Bump open-vulnerability-clients version
  pom.xml
Labels: defect, v4-port

#1672 Mirror container images to Docker Hub
  .github/workflows/_build-native-meta.yml
  .github/workflows/mirror-container-image.yml
  .github/workflows/publishJar.yml
  .github/workflows/release.yml
Labels: enhancement, ci

#1684 Port: Disable `include` tag for Pebble templates
  notification-publisher/src/main/java/org/dependencytrack/notification/config/PebbleConfiguration.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  notification-publisher/src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
  pom.xml
Labels: defect, security, v4-port
