Repository DependencyTrack/hyades, pull requests merged in 2025-04, with the labels that each got.

#1739 Document pagination support for `findings` REST endpoint
  docs/getting-started/changes-over-v4.md
Labels: documentation

#1751 Update schema for new `severity` enum type
  commons-persistence/src/main/resources/schema.sql
Labels: enhancement

#1764 Add ADR for consolidating user tables
  docs/architecture/decisions/006-consolidate-user-tables.md
  mkdocs.yml
Labels: documentation, architecture
